# Numpy exercises


#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [1]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [3]:
arr = np.zeros(10, dtype=np.int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [6]:
a = np.arange(5, dtype=np.int)
print(a)
b = np.array([1,2,3,4,5])
print(np.add(a,b))

[0 1 2 3 4]
[1 3 5 7 9]


#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [7]:
a = np.zeros(10, dtype=np.int)
a[5] = 1
print(a)

[0 0 0 0 0 1 0 0 0 0]


#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [9]:
a = np.arange(10,50,1, dtype=np.int)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [13]:
a = np.arange(51)
print(np.flip(a))


[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [14]:
print(np.array([[0,1,2],[3,4,5],[6,7,8]]))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի կոորդինատները:

In [16]:
a = np.array([1,2,0,0,4,0,0])
list1 = []
for i in range(0,len(a)):
    if a[i] == 0:
        list1.append(i)
print(list1)
        

[2, 3, 5, 6]


#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [25]:
np.random.randint(1,20,[3,3])

array([[ 8,  3, 11],
       [10,  4, 11],
       [10, 16, 18]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [34]:
np.random.seed(5)
a = np.random.randint(1,50,[10,10])
print("Max:",a.max())
print("Min:", a.min())

Max: 49
Min: 1


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [40]:
np.random.seed(5)
a = np.random.randint(0,100,30)
print(np.mean(a))

50.43333333333333


#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [43]:
a = np.arange(0,11)
print(a[3:8])

[3 4 5 6 7]


#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [48]:
np.random.seed(5)
a = np.random.randint(1,10,20)
print("Initial array:",a)
list1 = []
for i in a:
    if i < 5:
        list1.append(i*2)
print(list1)

Initial array: [4 7 7 1 9 5 8 1 1 8 2 6 8 1 2 5 7 3 2 3]
[8, 2, 2, 2, 4, 2, 4, 6, 4, 6]


#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [51]:
a = np.array([1,5,6,2,-2,23,45])
list1 = []
for i in range(0, len(a)):
    if a[i]%2 == 0:
        list1.append(i)
print("Indexes of even numbers:",list1)

Indexes of even numbers: [2, 3, 4]


#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [53]:
a = np.arange(1,20)
list1 = []
for i in a:
    if i%3 == 0:
        list1.append(i)
print("Indexes divisible by 3:",list1)

Indexes divisible by 3: [3, 6, 9, 12, 15, 18]


#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [65]:
a = np.array([np.arange(0,5),np.arange(0,5),np.arange(0,5),np.arange(0,5)])

print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 17. Create a 3x5 numpy array filled with random numbers from 1 to 10.

#### 17. Ստեղծեք 1-ից 10 պատահական թվերով լցված (3, 5) չափերով numpy array։

In [67]:
a = np.random.randint(1,11,[3,5])
print(a)

[[ 3  2  6  8  5]
 [ 4  2  8  4  2]
 [10  6  8  1 10]]


#### 18. Create a numpy array of size 10 filled with 0s and replace its 5th value with a 3.

#### 18. Ստեղծեք 10 չափի 0-ներով լցված numpy array ու փոխարինեք դրա 5-րդ արժեքը 3 թվով։

In [69]:
a = np.zeros(10)
a[5]=3
print(a)

[0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]


#### 19. Create a numpy array filled with numbers from 3 to 15 i.e. ([3, 4 … 13, 14])

#### 19. Ստեղծեք 3-ից 15 թվերից բաղկացած numpy array ([3, 4 … 13, 14])

In [ ]:
print(np.arange([3,15]))

#### 20. Write a function which gets a numpy array as an input and divides all of the array values by 2 over and over again, until the mean of the array numbers is <=5. Then, once the mean of the array numbers is <=5, the funtion returns the modified numpy array. 

#### 20. Գրեք ֆունկցիա, որը ստանում է numpy array ու բաժանում է դրա բոլոր արժեքները 2-ի այնքան ժամանակ մինչև որ դրանց միջին արժեքը լինի <=5։ Այնուհետև, հենց միջին արժեքը դառնում է <=5, ֆունկցիան վերադարձնում է փոփոխված numpy array-ը։

In [6]:
def div(arr):
    while np.mean(arr)>5:
            arr = arr/2
    return arr

In [7]:
a = np.array([10,11,12,13,14])
div(a)


array([2.5 , 2.75, 3.  , 3.25, 3.5 ])

#### 21. Write a function which gets a 5x4 numpy array filled with random numbers from 1 to 10 as an inputand returns 4 different numpy arrays which are the columns of the original numpy array. Write another similar function which returns 5 different numpy arrays which are rows of the original numpy array. 

#### 21. Գրեք ֆունկցիա, որը ստանում է 1-ից 10 պատահական թվերով լցված 5x4 numpy array ու վերադարձնում է 4 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի սյուներն են։ Գրեք նմանատիպ ֆունկցիա, որը վերադարձնում է 5 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի տողերն են։

In [55]:
def col(arr):
    for i in range(0, arr.shape[1]):
        print(arr[...,i])
        
def row(arr):
    for i in range(0, arr.shape[0]):
        print(arr[i,...])

In [64]:
np.random.seed(5)
a = np.random.randint(1,10, [5,4])

print("Original array:",'\n', a, '\n')
print("Rows:", row(a), '\n')
print("Columns:", col(a), '\n')

Original array: 
 [[4 7 7 1]
 [9 5 8 1]
 [1 8 2 6]
 [8 1 2 5]
 [7 3 2 3]] 

[4 7 7 1]
[9 5 8 1]
[1 8 2 6]
[8 1 2 5]
[7 3 2 3]
Rows: None 

[4 9 1 8 7]
[7 5 8 1 3]
[7 8 2 2 2]
[1 1 6 5 3]
Columns: None 

